---
abstract: 'A NoSQL document store with full text search for Moose objects using Elasticsearch as a backend.'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  CHI: '0'
  DateTime: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::Moose: '0'
  Test::More: '0.96'
  Test::Strict: '0'
  lib: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Elastic-Model
no_index:
  directory:
    - t
    - xt
    - bench
requires:
  Carp: '0'
  Class::Load: '0'
  Class::MOP: '0'
  Data::Dump: '0'
  Data::Dumper: '0'
  Devel::GlobalDestruction: '0'
  ElasticSearch::SearchBuilder: '0.18'
  JSON: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  MIME::Base64: '0'
  Moose: '2.06'
  Moose::Exporter: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::Types: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::Structured: '0'
  Scalar::Util: '0'
  Search::Elasticsearch: '1.12'
  Sub::Exporter: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
  Variable::Magic: '0.51'
  namespace::autoclean: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/clintongormley/Elastic-Model/issues
  repository: git://github.com/clintongormley/Elastic-Model.git
version: '0.50'
